{
  "modified": "2024-06-13T19:24:11.289Z",
  "published": "2024-03-19T15:44:28.989Z",
  "schema_version": "1.5.0",
  "id": "PSF-2024-1",
  "aliases": [
    "CVE-2023-6597"
  ],
  "details": "An issue was found in the CPython `tempfile.TemporaryDirectory` class affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.\n\nThe tempfile.TemporaryDirectory class would dereference symlinks during cleanup of permissions-related errors. This means users which can run privileged programs are potentially able to modify permissions of files referenced by symlinks in some circumstances.\n",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "81c16cd94ec38d61aa478b9a452436dc3b1b524d"
            },
            {
              "fixed": "6ceb8aeda504b079fef7a57b8d81472f15cdd9a5"
            },
            {
              "fixed": "5585334d772b253a01a6730e8202ffb1607c3d25"
            },
            {
              "fixed": "8eaeefe49d179ca4908d052745e3bb8b6f238f82"
            },
            {
              "fixed": "d54e22a669ae6e987199bb5d2c69bb5a46b0083b"
            },
            {
              "fixed": "02a9259c717738dfe6b463c44d7e17f2b6d2cb3a"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/81c16cd94ec38d61aa478b9a452436dc3b1b524d"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/6ceb8aeda504b079fef7a57b8d81472f15cdd9a5"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/5585334d772b253a01a6730e8202ffb1607c3d25"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/8eaeefe49d179ca4908d052745e3bb8b6f238f82"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/d54e22a669ae6e987199bb5d2c69bb5a46b0083b"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/02a9259c717738dfe6b463c44d7e17f2b6d2cb3a"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/python/cpython/issues/91133"
    },
    {
      "type": "ADVISORY",
      "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/Q5C6ATFC67K53XFV4KE45325S7NS62LD/"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2024/03/msg00025.html"
    },
    {
      "type": "WEB",
      "url": "http://www.openwall.com/lists/oss-security/2024/03/20/5"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3IGRX54M7RNCQOXVQO5KQKTGWCOABIM/"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U5VHWS52HGD743C47UMCSAK2A773M2YE/"
    }
  ],
  "database_specific": {
    "cwe_ids": []
  }
}