{
  "schema_version": "1.5.0",
  "id": "PSF-0000-CVE-2024-0397",
  "aliases": [
    "CVE-2024-0397"
  ],
  "published": "2024-06-17T15:09:40.896Z",
  "modified": "2024-06-17T15:11:16.322Z",
  "details": "A defect was discovered in the Python \u201cssl\u201d module where there is a memory\nrace condition with the ssl.SSLContext methods \u201ccert_store_stats()\u201d and\n\u201cget_ca_certs()\u201d. The race condition can be triggered if the methods are\ncalled at the same time as certificates are loaded into the SSLContext,\nsuch as during the TLS handshake with a certificate directory configured.\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "01c37f1d0714f5822d34063ca7180b595abf589d"
            },
            {
              "fixed": "29c97287d205bf2f410f4895ebce3f43b5160524"
            },
            {
              "fixed": "37324b421b72b7bc9934e27aba85d48d4773002e"
            },
            {
              "fixed": "542f3272f56f31ed04e74c40635a913fbc12d286"
            },
            {
              "fixed": "b228655c227b2ca298a8ffac44d14ce3d22f6faa"
            },
            {
              "fixed": "bce693111bff906ccf9281c22371331aaff766ab"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://github.com/python/cpython/issues/114572"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/pull/114573"
    },
    {
      "type": "ADVISORY",
      "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/01c37f1d0714f5822d34063ca7180b595abf589d"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/29c97287d205bf2f410f4895ebce3f43b5160524"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/37324b421b72b7bc9934e27aba85d48d4773002e"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/542f3272f56f31ed04e74c40635a913fbc12d286"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/b228655c227b2ca298a8ffac44d14ce3d22f6faa"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/bce693111bff906ccf9281c22371331aaff766ab"
    }
  ],
  "database_specific": {
    "cwe_ids": []
  }
}